import type { Metadata } from "next";
import { Noto_Serif_Bengali} from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const notoSarifBengali = Noto_Serif_Bengali({
  subsets: ["latin", "bengali"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${notoSarifBengali.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header />
        {children}</body>
        {/* <div>FOOTER</div> */}
    </html>
  );
}
